Message to sign payload
vultisig/commondata pull request #20
Opened 2024-11-18 05:00 UTC by flypaper0

### Parameters

**method** - _personal_sign_, _eth_signTypeData_v4_ or other supported signing method 
**message** - message to sign UTF8 string

### Example 
```
{
  "method": "personal_sign",
  "message": "Hey vulti!"
}
```

### Ref: 
https://github.com/vultisig/vultisig-ios/issues/1520
https://docs.metamask.io/wallet/how-to/sign-data/#use-eth_signtypeddata_v4
https://docs.metamask.io/wallet/reference/json-rpc-methods/personal_sign/

2024-11-18 05:08 UTC, johnnyluo commented on proto/vultisig/keysign/v1/keysign_message.proto
> +  optional MessageToSignPayload message_to_sign_payload = 33;
instead of add an optional message here , I think we probably should just define a "CustomMessage" , and add it to `KeysignMessage`

2024-11-18 21:07 UTC, johnnyluo commented on proto/vultisig/keysign/v1/keysign_message.proto
> +  optional KeysignPayload keysign_payload = 5;
don't change this , all fields in proto3 is optional by default.

2024-11-18 21:08 UTC, johnnyluo requested changes
Can you please run `buf generate` to generate swift and golang files as well

2024-11-18 21:52 UTC, johnnyluo commented on proto/vultisig/keysign/v1/custom_message_payload.proto
> +  string method = 1;
why we need `method`?

2024-11-19 16:02 UTC, flypaper0 commented
Leaving this PR unmerged during client side integration

2024-12-11 21:04 UTC, johnnyluo approved these changes
LGTM

2024-12-12 07:16 UTC, merged